### ISSUE TITLE
filesystem=home instead of filesystem=host

### ISSUE THREAD

**Issue by kowalski7cc** [flathub/sh.ppy.osu#10]
The readme states that "If you want to be able to access all files and directories in your home directory, use Flatseal from flatpak, or `sudo flatpak override sh.ppy.osu --filesystem=host`", but it should be `sudo flatpak override sh.ppy.osu --filesystem=home`

**Comment by BiteDasher** [comment]
Fixed in 62f3647ee4a38069797dbce4b002d9b6435d745f
