### ISSUE TITLE
Replace --socket=x11 permission with --socket=fallback-x11

### ISSUE THREAD

**Issue by rugk** [flathub/sh.ppy.osu#36]
The GNOME Software considers applications requiring x11 as unsafe. There's a way to declare it uses Wayland, but can use X11 as a fallback, on desktop environments where Wayland doesn't run.

More info here:
https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/770#note_1136536

copied from https://github.com/flathub/org.gnome.Evolution/issues/49

**Comment by rugk** [comment]
I guess this discussion is running in https://github.com/ppy/osu/issues/18273 currently…

Also saw that. Oh but no, they don't give up wayland, they give up:
> Looks like upstream is plain giving up on wayland on older distros,

https://github.com/libsdl-org/SDL/pull/5429

Anyway I did overwrites locally and you can use XWayland with `fallback-x11`. (After all this was causing https://github.com/ppy/osu/issues/18288 for me and it worked with XWayland there.)

**Comment by Alexmitter** [comment]
> I don't see any benefit of games using pure wayland, even SDL reverted back to xwayland for now.

While the backend is not yet fully stable for some applications and due to that, reverted to defaulting to Xwayland. The benefit is very obvious playing the game on a wayland shell. You can always try Xwayland and the native wayland backend and feel the difference in gameplay feel.

**Comment by Thesola10** [comment]
Fractional scaling is a good example of a feature that's properly supported on Wayland but not X11. I've been playing on pure Wayland and have had no issues on the latest versions.

**Comment by Etaash-mathamsetty** [comment]
another reason would the new tearing protocol

**Comment by orowith2os** [comment]
@rugk could you update your PR to use the SDL2 from shared-modules? There's an SDL2-with-libdecor manifest there so that it has better compatibility, and ideally should fix up enough issues that the flatpak can realistically use Wayland by default. 

Numerous external sources also suggest using native Wayland for osu as well.

**Comment by orowith2os** [comment]
Made a new PR that touches up on the work done by rugk, and some notes from me:

SDL3 has started development, so I'd say it's safe to use SDL2 with Wayland by default now. It seems to be mature enough. If any complaints are had, the end user can manually override it anyways, it's not too much work.
