### ISSUE TITLE
Does not (always) use/start with fullscreen on Wayland

### ISSUE THREAD

**Issue by rugk** [flathub/sh.ppy.osu#38]
## STR

When you initially start the game and when you switch to another app (Super key and switch back) the game window is only shown in the lower left part of the screen. The rest is black. (Full HD screen here)

### What happens

![badscreen](https://user-images.githubusercontent.com/11966684/168475587-3bc68dd3-b348-41d3-82db-56731bc5ffb8.png)

### What should happen

Always full-screen by default/when you switch back.

## Workaround

In the settings, you can switch between the "screens" (it still shows on the same screen, I have no idea what that means. At least I have two physical screens connected, but AFAIK under Wayland apps cannot decide their window position, so maybe that's the reason here.).
No matter what "screen" you chose, it switched it to "proper" fullscreen.

![workaorund-fullscreen](https://user-images.githubusercontent.com/11966684/168475626-4521025f-a516-460a-8088-98de2ae644cd.png)

## System
Fedora Linux 36 (Workstation Edition)
Flatpak 1.12.7
GNOME 42.1
Wayland

```
$ flatpak info sh.ppy.osu

osu! - A free-to-win rhythm game. Rhythm is just a *click* away!

          ID: sh.ppy.osu
         Ref: app/sh.ppy.osu/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2022.515.0
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 267.7�MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 2fcc18352a03372644d2bd1fe3632b39432cb140222fcd0b03308e5a94df9584
      Parent: 4fa7e9cde27ac360333cde1c67021b30d199e264568168121fc2f6df199f278c
     Subject: Update osu.AppImage to 2022.515.0 (6fa20c67)
        Date: 2022-05-15 05:57:55 +0000
```

**Comment by peppy** [comment]
you're probably not going to get any support here. if you're interested in fixing linux issues, please investigate at a source level in SDL and help them there.

**Comment by rugk** [comment]
This is not a support request, rather a bug report. But thanks for the SDL pointer. …[or any of the other issues](https://github.com/libsdl-org/SDL/issues?q=is%3Aissue+is%3Aopen+wayland+fullscreen)

I found https://github.com/libsdl-org/SDL/issues/5437, which is relatively new and may be related to this and not yet using a fixed version.

Likely unrelated: https://github.com/libsdl-org/SDL/issues/3135

**Comment by rugk** [comment]
Reported upstream now, respectively even found an upstream bug report about it: https://github.com/ppy/osu/issues/18288#issuecomment-1126996476

So does not seem to be a Flatpak-specific issue…
