### ISSUE TITLE
Got "A" But no rank change?

### ISSUE THREAD

**Issue by floatyHorizonOfficial** [flathub/sh.ppy.osu#79]
Hey, so a few days ago I got an "A" rank in the level "Evo"(Ranked, 2.8*(If I remember correctly)), yet I got no PP or anything from beating it, not even my friend(Who's a good Osu! player) understood what could cause the problem. And no, there was no Error Popup.
My friend plays on Windows and I play on Linux(in case you were wondering).
Is it a software bug or something I missed in my research to try to fix it?

**Comment by peppy** [comment]
Lazer has limited leaderboard support right now. It will show in-game but only recent plays and overall statistics (ie. not PP) will update on your profile. This will improve as things go forward.

**Comment by floatyHorizonOfficial** [comment]
oh ok.
