### ISSUE TITLE
Audio options for PipeWire and JACK not showing up

### ISSUE THREAD

**Issue by Thesola10** [flathub/sh.ppy.osu#80]
I can only select direct ALSA access or Pulseaudio when running through Flatpak. I have a working install of PipeWire, and the AppImage version correctly reports JACK and PipeWire as options.

This is annoying seeing as PipeWire is the only reliable way to get low latency audio on Linux, and if I understand correctly, it should be relayed through the Flatpak sandbox, right?

**Comment by Thesola10** [comment]
`LD_DEBUG=libs` reports that osu does open `libjack.so.0` (owned by PipeWire), but somehow doesn't "see" the PipeWire server, even when manually bridged through using `--filesystem=xdg-run/pipewire-0`??

**Comment by TheComputerGuy96** [comment]
The BASS audio library used by osu!(lazer) only supports ALSA for audio output (so PulseAudio/PipeWire have a compatibility layer)

**Comment by Thesola10** [comment]
@TheComputerGuy96 Okay, that was exactly correct actually, another thorough `strace` revealed that my system had additional ALSA config files for Pipewire and JACK, which this Flatpak does not have. Should this issue be upstreamed to FreeDesktop Runtime?

**Comment by Thesola10** [comment]
This could be worked around by:

1. Shipping `/etc/alsa/conf.d/50-pipewire.conf` from the Pipewire Project, likely in `/app/etc/alsa/conf.d`
2. Appending `:/app/etc/alsa/conf.d` to the `$ALSA_CONFIG_PATH` env var.

**Comment by Thesola10** [comment]
Upstream issue filed to Freedesktop SDK: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1722

**Comment by Thesola10** [comment]
Upstream has been merged, this will be closed once this package is updated to the latest Runtime, or the fix is backported.

**Comment by TheComputerGuy96** [comment]
I think the issue can be closed as completed: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/d576f75f34c0975db22f0f5b61900c2969a24e21 (there have been multiple 23.08 versions since then)
