### ISSUE TITLE
200+ Encountered tablet errors

### ISSUE THREAD

**Issue by XoloitzcuintiI** [flathub/sh.ppy.osu#94]
Just installed osu! for the first time on my Fedora 37 installation, and was met with 224 errors that reads:

> Encountered tablet error:
> "DeviceUnauthroizedAccessException"
> Not permitted to open HID class device at /dev/hidraw16

Happens on every time I launch osu!

![Screenshot from 2023-02-24 23-37-14](https://user-images.githubusercontent.com/84434484/221338719-4350935f-11a3-435a-ab55-69e8c40ebcc2.png)

![Screenshot from 2023-02-24 23-37-31](https://user-images.githubusercontent.com/84434484/221338722-948ec0ac-695a-4afa-bd53-d7891bb632b1.png)

**Comment by developomp** [comment]
Are you sure this is a flatpak-specific issue?
You might wanna open a issue over at https://github.com/ppy/osu and close this one.

**Comment by peppy** [comment]
And more so, do a google search, because I'm pretty sure a solution exists for this which should be very obvious to a linux user.
